### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by manojsai2** [ChangyuChen347/semi-offline-RL#2]
I had run 17,000 steps and stopped running. Now I want to continue from 17,000. What do I need to change?

**Comment by ChangyuChen347** [comment]
The default storing path of checkpoints is **./model_output**. You can change the line **--recover model_output/cnndm_base_model** in the script to **--recover model_output/${your checkpoint}** and then start training.

**Comment by manojsai2** [comment]
I have done same thing but it is running from start....can you tell what can i do further?

**Comment by ChangyuChen347** [comment]
Currently, there is no storage for the optimizer, so if you want to restore the optimizer's state, it might not be possible. As you mentioned, the approach described above indeed involves training from scratch. If you want to avoid retraining on the same data, you can modify the seed for the second run. The main issue is that this code does not follow the default checkpoint storage and resume logic of the Transformer Trainer. If you are familiar with the Transformer Trainer, you can modify the relevant storage code to match the official trainer's default method. If you're not very familiar with it, I can make these changes to the code within the next week.

**Comment by ChangyuChen347** [comment]
If you are worried about needing to retrain for another 60 epochs, you actually don't need to be concerned. The end epoch in the script is set to 60, but it's generally unnecessary to train for that long. Convergence often occurs much earlier. It's fine to end your experiments once you notice that the metric on the dev set has converged.

**Comment by manojsai2** [comment]
Thank you for ur response .  can you give more detail about transformer trainer and also can i known the explanation of this sample result section that is generated in middle of the step that i did not understand?
NFO:trainer.Trainer.rl_trainer:At step 16999, his_greedy_rewards rouge = 0.23486627638339996
INFO:trainer.Trainer.rl_trainer:At step 16999, his_ce_loss 3.6595513820648193
INFO:trainer.Trainer.rl_trainer:At step 16999, his_rl_loss -0.09631047397851944
INFO:trainer.Trainer.rl_trainer:At step 16999, his_loss 1.795048713684082
INFO:trainer.Trainer.rl_trainer:At step 16999, his_dif_cont_rate
INFO:trainer.Trainer.rl_trainer:At step 16999, gram_acc: 2:0.4563785791397095, 3:0.3447173237800598, 4:0.2546575367450714
INFO:trainer.Trainer.rl_trainer:name: rouge, reward: 0.23768004775047302
INFO:trainer.Trainer.rl_trainer:to_print_dist: [(['ĠEdison'], 0.051944777), (['ĠBieber'], 0.048740238), (['ĠHuckabee'], 0.046016756), (['ĠMour'], 0.044232905), (['Ġsecession'], 0.042606056), (['ĠGiul'], 0.04101235), (['ĠScarborough'], 0.04040253), (['ĠLore'], 0.03881165), (['Ġfracking'], 0.03787637), (['ĠNavajo'], 0.037350737), (['ĠSantana'], 0.037193634), (['ĠBolt'], 0.035947498), (['Ġchemically'], 0.035404768), (['ĠGmail'], 0.034756947), (['ĠCoy'], 0.034076516), (['Ġtyre'], 0.03405528), (['ĠValues'], 0.034027122), (['expected'], 0.03341639), (['.'], 0.032913875), (['ĠFurn'], 0.031973332)]
INFO:trainer.Trainer.rl_trainer:to_print_dist: [(['Ġ..............'], -0.0274614), (['acan'], -0.027680933), (['Malley'], -0.02820873), (['Represent'], -0.028564358), (['oso'], -0.029004049), (['..................'], -0.029235905), (['Sad'], -0.029281143), (['ĠKass'], -0.030630859), (['Ġcircumcision'], -0.030816237), (['ĠSteps'], -0.031570278), (['677'], -0.032494813), (['ĠHulu'], -0.033310086), (['ĠKinect'], -0.03515471), (['........................'], -0.03958857), (['Ġcove'], -0.039615538), (['ĠMcK'], -0.040337894), (['................................'], -0.044292204), (['ĠGlob'], -0.052197922), (['note'], -0.06023857), (['................................................................'], -0.07173929)]
INFO:trainer.Trainer.rl_trainer:to_print_count top 20: [(['.'], 0.032913875), ([','], 0.017126648), (['Ġthe'], 0.01684632), (['Ġto'], 0.012622327), (['Ġin'], 0.01147335), (['Ġher'], 0.009950391), (['Ġa'], 0.008804126), (['Ġof'], 0.007386468), (['Ġsays'], 0.0067562265), (["'s"], 0.006214062), (['Ġwas'], 0.0053902725), (['ĠU'], 0.005246236), (['Ġhis'], 0.0051912586), (['Ġand'], 0.004559759), (['The'], 0.0043942444), (['Ġsay'], 0.0041342075), (['-'], 0.0039235405), (['Ġwill'], 0.00306142), (['Ġfound'], 0.0028742042), (['Ġbe'], 0.0028070924)]
INFO:trainer.Trainer.rl_trainer:to_print_count last 20: [(['Ġthis'], -0.0022294652), (['Ġalso'], -0.0022452937), (['Ġover'], -0.00240469), (['Ġagainst'], -0.0024122442), (['Ġan'], -0.002437369), ([';'], -0.002452449), (['Ġits'], -0.0024875614), (['Ġset'], -0.0024961375), (['Ġwho'], -0.0029681604), (['Ġthat'], -0.0030050494), (['Ġabout'], -0.003044252), (['Ġbefore'], -0.0031121196), ([':'], -0.0031923635), (['Ġduring'], -0.003234965), (['Âł'], -0.0033055206), (['Ġwhen'], -0.0035111948), (['Ġbut'], -0.0039385613), (["'"], -0.004333234), (['Ġor'], -0.005391305), (['"'], -0.0074252943)]

**Comment by manojsai2** [comment]
can you clarify how results coming in running code and the results in paper compared?

**Comment by ChangyuChen347** [comment]
The code includes a naive storage implementation that I wrote myself. You can refer to the official method at https://github.com/huggingface/transformers/blob/98e8062df3cf82b367e8a243963e4afb0d9d3407/src/transformers/trainer.py#L3173, which includes functions like _save_checkpoint() and other related calls in the chain. These functions are well encapsulated.

Regarding the printed results, we calculate the reward for the sentences obtained from sampling. After multiple samplings, we can compute the advantage for each token. Here, to_print_dist and to_print_count are dictionaries that record the advantage of each sampled token; the key is the token and the value are the advantages. to_print_count only retains tokens that appear frequently, while to_print_dist contains all tokens. The printed output shows the top 20 or last 20 tokens sorted by advantage. You can refer to the computation code for these dictionaries in trainer/Trainer/rl_trainer.py.

The purpose of printing this information is to see if there are any tokens that show a preference due to the reward scheme. For example, in our previous experiments, for a reward based on ad click-through rates, the token 'free' generally appears near the top. However, for the ROUGE reward, we did not find any significant preferred tokens.

> Thank you for ur response . can you give more detail about transformer trainer and also can i known the explanation of this sample result section that is generated in middle of the step that i did not understand? NFO:trainer.Trainer.rl_trainer:At step 16999, his_greedy_rewards rouge = 0.23486627638339996 INFO:trainer.Trainer.rl_trainer:At step 16999, his_ce_loss 3.6595513820648193 INFO:trainer.Trainer.rl_trainer:At step 16999, his_rl_loss -0.09631047397851944 INFO:trainer.Trainer.rl_trainer:At step 16999, his_loss 1.795048713684082 INFO:trainer.Trainer.rl_trainer:At step 16999, his_dif_cont_rate INFO:trainer.Trainer.rl_trainer:At step 16999, gram_acc: 2:0.4563785791397095, 3:0.3447173237800598, 4:0.2546575367450714 INFO:trainer.Trainer.rl_trainer:name: rouge, reward: 0.23768004775047302 INFO:trainer.Trainer.rl_trainer:to_print_dist: [(['ĠEdison'], 0.051944777), (['ĠBieber'], 0.048740238), (['ĠHuckabee'], 0.046016756), (['ĠMour'], 0.044232905), (['Ġsecession'], 0.042606056), (['ĠGiul'], 0.04101235), (['ĠScarborough'], 0.04040253), (['ĠLore'], 0.03881165), (['Ġfracking'], 0.03787637), (['ĠNavajo'], 0.037350737), (['ĠSantana'], 0.037193634), (['ĠBolt'], 0.035947498), (['Ġchemically'], 0.035404768), (['ĠGmail'], 0.034756947), (['ĠCoy'], 0.034076516), (['Ġtyre'], 0.03405528), (['ĠValues'], 0.034027122), (['expected'], 0.03341639), (['.'], 0.032913875), (['ĠFurn'], 0.031973332)] INFO:trainer.Trainer.rl_trainer:to_print_dist: [(['Ġ..............'], -0.0274614), (['acan'], -0.027680933), (['Malley'], -0.02820873), (['Represent'], -0.028564358), (['oso'], -0.029004049), (['..................'], -0.029235905), (['Sad'], -0.029281143), (['ĠKass'], -0.030630859), (['Ġcircumcision'], -0.030816237), (['ĠSteps'], -0.031570278), (['677'], -0.032494813), (['ĠHulu'], -0.033310086), (['ĠKinect'], -0.03515471), (['........................'], -0.03958857), (['Ġcove'], -0.039615538), (['ĠMcK'], -0.040337894), (['................................'], -0.044292204), (['ĠGlob'], -0.052197922), (['note'], -0.06023857), (['................................................................'], -0.07173929)] INFO:trainer.Trainer.rl_trainer:to_print_count top 20: [(['.'], 0.032913875), ([','], 0.017126648), (['Ġthe'], 0.01684632), (['Ġto'], 0.012622327), (['Ġin'], 0.01147335), (['Ġher'], 0.009950391), (['Ġa'], 0.008804126), (['Ġof'], 0.007386468), (['Ġsays'], 0.0067562265), (["'s"], 0.006214062), (['Ġwas'], 0.0053902725), (['ĠU'], 0.005246236), (['Ġhis'], 0.0051912586), (['Ġand'], 0.004559759), (['The'], 0.0043942444), (['Ġsay'], 0.0041342075), (['-'], 0.0039235405), (['Ġwill'], 0.00306142), (['Ġfound'], 0.0028742042), (['Ġbe'], 0.0028070924)] INFO:trainer.Trainer.rl_trainer:to_print_count last 20: [(['Ġthis'], -0.0022294652), (['Ġalso'], -0.0022452937), (['Ġover'], -0.00240469), (['Ġagainst'], -0.0024122442), (['Ġan'], -0.002437369), ([';'], -0.002452449), (['Ġits'], -0.0024875614), (['Ġset'], -0.0024961375), (['Ġwho'], -0.0029681604), (['Ġthat'], -0.0030050494), (['Ġabout'], -0.003044252), (['Ġbefore'], -0.0031121196), ([':'], -0.0031923635), (['Ġduring'], -0.003234965), (['Âł'], -0.0033055206), (['Ġwhen'], -0.0035111948), (['Ġbut'], -0.0039385613), (["'"], -0.004333234), (['Ġor'], -0.005391305), (['"'], -0.0074252943)]

**Comment by ChangyuChen347** [comment]
> can you clarify how results coming in running code and the results in paper compared?

The checkpoint provided in readme section 5 Checkpoints and Static Datasets should be largely consistent with the results of the Table 1 in the paper. You can try running the tests using the commands provided in section 4 Evaluation. You can also use your own trained model for evaluation.

**Comment by manojsai2** [comment]
Thank you very much for your valuable information.
